### ISSUE TITLE
Support for servicebus administration client

### ISSUE THREAD

**Issue by ksgopal4** [PejmanNik/lazvard-message#10]
Thanks for creating a much needed servicebus emulator. I was wondering if you see ever adding features to support servicebus admin client? https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.administration.servicebusadministrationclient?view=azure-dotnet

**Comment by PejmanNik** [comment]
Hi, Thank you 🤩 I don’t have any objections to it, but the only thing preventing me from spending time on it is that Microsoft is developing an official version of the simulation, with an ETA by the end of the year. I'm not sure if it's worth spending more time on this library 😔

**Comment by ksgopal4** [comment]
OK, didnt realise that, agree, that makes sense then.
