### ISSUE TITLE
Queues not working

### ISSUE THREAD

**Issue by adrian-gheorghe** [PejmanNik/lazvard-message#11]
Hello

I am trying to use your emulator (running a container with the Docker image) by configuring some queues alongside some topics + subscriptions but the queues are not being created. Even with the default configuration, the queues do not seem to be created

Is this not supported or am I just doing it wrong?

Thank you

**Comment by PejmanNik** [comment]
Both queues and topics use the same exact code, so it should work as expected. Is there any error? Are the topics working?

**Comment by PejmanNik** [comment]
I noticed that the logger was emitting the queue names, which may indicate that the queues were not created. However, it was only an issue in the logging mechanism, which was fixed in version 0.5.0. Please feel free to reopen the issue if you are still experiencing this issue
