### ISSUE TITLE
nuget package

### ISSUE THREAD

**Issue by wmaryszczak** [PejmanNik/lazvard-message#3]
Hi, Please consider to have nuget package with `Lazvard.Message.Cli.Server` published on nuget.org. It will allow to have the server embedded in xunit project as you did in `Lazvard.Message.Amqp.Server.IntegrationTests`

Thank you in advance

**Comment by PejmanNik** [comment]
Hi, I published the Nuget package manually, for now:
```Lazvard.Message.Amqp.Server```
